# MySQL. Versions 5.5.8 and up are supported.
default: &default
  adapter: postgresql
  #adapter: mysql2
  encoding: unicode
  #encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:  <%= ENV["MASTER_USER"] %>
  password:  <%= ENV["MASTER_PASS"] %>
  host: ec2-34-204-22-76.compute-1.amazonaws.com
  port: 5432
#  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: contact_list_development

test:
  <<: *default
  database: contact_list_test

production:
  <<: *default
  database: contact_list_production
  username: <%= ENV["MASTER_USER"] %>
  password: <%= ENV["MASTER_PASS"] %>
