# MySQL. Versions 5.5.8 and up are supported.
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:  <%= ENV["MASTER_USER"] %>
  password:  <%= ENV["MASTER_PASS"] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: contact_list_development

test:
  <<: *default
  database: contact_list_test

production:
  <<: *default
  database: contact_list_production
  username: <%= ENV["MASTER_USER"] %>
  password: <%= ENV["MASTER_PASS"] %>
